import type { MatchCandidateGroup } from '@/types/hitl'

export const rejectionReasons = [
  'Different VAT / registration identity',
  'Different legal entity',
  'Address conflict too strong',
  'Phone / email mismatch',
  'Grouped by mistake',
  'Insufficient evidence',
]

export const REVIEWERS = [
  { id: 'r1', name: 'Elen Axis' },
  { id: 'r2', name: 'Marcus Voss' },
  { id: 'r3', name: 'Amina Noor' },
]

export const ROLE_PERMISSIONS = [
  {
    role: 'Admin',
    desc: 'Full access to users, settings, analytics, and review controls',
    perms: ['Review', 'Analytics', 'Manage', 'Settings'],
  },
  {
    role: 'Senior Reviewer',
    desc: 'Can review, inspect analytics, and supervise queue decisions',
    perms: ['Review', 'Analytics'],
  },
  {
    role: 'Reviewer',
    desc: 'Can process assigned candidate groups and review suggestions',
    perms: ['Review'],
  },
  {
    role: 'Trainee',
    desc: 'Limited review participation under supervision',
    perms: ['Review'],
  },
]

export const ACTIVITY_LOG = [
  {
    id: 'a1',
    type: 'confirm',
    text: '<b>Elen Axis</b> confirmed group GRP-1001 with registry as golden source.',
    time: '5 minutes ago',
  },
  {
    id: 'a2',
    type: 'reject',
    text: '<b>Marcus Voss</b> rejected group GRP-1002 due to registration mismatch.',
    time: '18 minutes ago',
  },
  {
    id: 'a3',
    type: 'system',
    text: 'Auto-assignment redistributed 8 pending groups across active reviewers.',
    time: '35 minutes ago',
  },
  {
    id: 'a4',
    type: 'retrain',
    text: 'Model precision threshold updated after retraining pipeline completed.',
    time: '1 hour ago',
  },
]

export const MATCH_GROUPS: (MatchCandidateGroup & {
  projects?: {
    id?: string
    source_system?: string
    source_id?: string
    project_name?: string
    project_title?: string
    project_state?: string
    project_start_date?: string
    project_end_date?: string
    company?: string
    source_hint?: string
    project_code?: string
    owner_name?: string
    owner_email?: string
    description?: string
    source_description?: string
  }[]
})[] = [
  {
    id: 'GRP-1001',
    confidence: 0.93,
    status: 'suggested',
    assignee: 'Elen Axis',
    reasons: [
      { text: 'Exact registration number match', score: 1, strength: 'strong' },
      { text: 'Business name highly similar', score: 0.91, strength: 'strong' },
      { text: 'Country matches', score: 0.7, strength: 'medium' },
      { text: 'Address formatting differs slightly', score: -0.2, strength: 'weak' },
    ],
    records: [
      {
        id: 'rec-1',
        source_system: 'registry',
        source_id: 'REG-001',
        entity_type: 'company',
        name: 'Trinidad Wiseman OÜ',
        // observed_at: '2026-03-20T09:30:00Z',
        raw_payload_json: {
          registry_status: 'active',
          source_confidence: 0.98,
        },
        record_subtype: 'legal_entity',
        record_family: 'organization',
        anchor_name: 'Trinidad Wiseman',
        client_name: 'Trinidad Wiseman OÜ',
        client_name_primary: 'Trinidad Wiseman OÜ',
        country: 'Estonia',
        address: 'Harju maakond, Tallinn',
        sector: 'Technology',
        reg_no: 'EE123456789',
        field_values: {
          phone: '+372 600 1111',
          email: 'info@trinidadwiseman.ee',
        },
      },
      {
        id: 'rec-2',
        source_system: 'crm',
        source_id: 'CRM-2188',
        entity_type: 'company',
        name: 'Trinidad Wiseman OU',
        // observed_at: '2026-03-19T16:10:00Z',
        raw_payload_json: {
          account_owner: 'Marcus Voss',
          lifecycle_stage: 'customer',
        },
        record_subtype: 'client_account',
        record_family: 'organization',
        anchor_name: 'Trinidad Wiseman',
        client_name: 'Trinidad Wiseman OU',
        client_name_primary: 'Trinidad Wiseman OÜ',
        country: 'Estonia',
        address: 'Tallinn, Harju',
        sector: 'Technology',
        reg_no: 'EE123456789',
        field_values: {
          phone: '+372 600 1111',
          email: 'info@trinidadwiseman.ee',
        },
      },
      {
        id: 'rec-3',
        source_system: 'website',
        source_id: 'WEB-882',
        entity_type: 'company',
        name: 'Trinidad Wiseman',
        // observed_at: '2026-03-18T12:00:00Z',
        raw_payload_json: {
          page_type: 'contact_page',
        },
        record_subtype: 'public_web_profile',
        record_family: 'organization',
        anchor_name: 'Trinidad Wiseman',
        client_name: 'Trinidad Wiseman',
        client_name_primary: 'Trinidad Wiseman OÜ',
        country: 'Estonia',
        address: 'Tallinn',
        sector: 'Technology',
        reg_no: 'EE123456789',
        field_values: {
          email: 'info@trinidadwiseman.ee',
        },
      },
    ],
    projects: [
      {
        id: 'proj-1001-a',
        source_system: 'Smartsheet',
        source_id: '1301006',
        project_name: 'E1 & IP UX study',
        project_title: 'E1 & IP UX study',
        project_state: 'Confirmed',
        project_start_date: '2016-12-18',
        project_end_date: '2017-01-31',
        company: 'Mascus',
        project_code: '',
        owner_name: 'Kadi Saar',
        owner_email: 'kadi.saar@mascus.example',
        description: 'UX study project context linked from Smartsheet preview data.',
      },
    ],
  },
  {
    id: 'GRP-1002',
    confidence: 0.71,
    status: 'suggested',
    assignee: 'Marcus Voss',
    reasons: [
      { text: 'Name similarity moderate', score: 0.55, strength: 'medium' },
      { text: 'Country matches', score: 0.4, strength: 'medium' },
      { text: 'Phone differs', score: -0.5, strength: 'strong' },
      { text: 'Registration number missing in one source', score: -0.2, strength: 'weak' },
    ],
    records: [
      {
        id: 'rec-4',
        source_system: 'erp',
        source_id: 'ERP-771',
        entity_type: 'company',
        name: 'Eco Match BV',
        // observed_at: '2026-03-21T10:15:00Z',
        raw_payload_json: {
          supplier_status: 'active',
        },
        record_subtype: 'supplier_master',
        record_family: 'organization',
        anchor_name: 'Eco Match',
        client_name: 'Eco Match BV',
        client_name_primary: 'Eco Match BV',
        country: 'Netherlands',
        address: 'Rotterdam',
        sector: 'Sustainability',
        reg_no: 'NL99887766B01',
        field_values: {
          phone: '+31 10 111 2222',
          email: 'ops@ecomatch.nl',
        },
      },
      {
        id: 'rec-5',
        source_system: 'crm',
        source_id: 'CRM-992',
        entity_type: 'company',
        name: 'EcoMatch B.V.',
        // observed_at: '2026-03-20T14:00:00Z',
        raw_payload_json: {
          lifecycle_stage: 'lead',
        },
        record_subtype: 'prospect_account',
        record_family: 'organization',
        anchor_name: 'EcoMatch',
        client_name: 'EcoMatch B.V.',
        client_name_primary: 'EcoMatch B.V.',
        country: 'Netherlands',
        address: 'Rotterdam',
        sector: 'Sustainability',
        reg_no: '',
        field_values: {
          phone: '+31 10 111 9999',
          email: 'hello@ecomatch.nl',
        },
      },
    ],
    projects: [
      {
        id: 'proj-1002-a',
        source_system: 'Smartsheet',
        source_id: '1300889',
        project_name: 'Tallink: Smart Port',
        project_title: 'Tallink: Smart Port',
        project_state: 'Confirmed',
        project_start_date: '2017-01-01',
        project_end_date: '2017-12-31',
        company: 'Tallink',
        project_code: '39',
        owner_name: 'Mari Tamm',
        owner_email: 'mari.tamm@tallink.example',
        description: 'Frontend preview of a Tallink project grouped under one entity.',
      },
      {
        id: 'proj-1002-b',
        source_system: 'Smartsheet',
        source_id: '1300887',
        project_name: 'Tallink: Shopping',
        project_title: 'Tallink: Shopping',
        project_state: 'Confirmed',
        project_start_date: '2017-01-01',
        project_end_date: '2017-12-31',
        company: 'Tallink',
        project_code: '38',
        owner_name: 'Rasmus Hein',
        owner_email: 'rasmus.hein@tallink.example',
        description: 'Second project shown to test multi-project grouping on the frontend.',
      },
    ],
  },
  {
    id: 'GRP-1003',
    confidence: 0.58,
    status: 'suggested',
    assignee: 'Amina Noor',
    reasons: [
      { text: 'Client name partially overlaps', score: 0.44, strength: 'medium' },
      { text: 'Anchor name differs', score: -0.35, strength: 'medium' },
      { text: 'Address differs significantly', score: -0.66, strength: 'strong' },
      { text: 'Country matches', score: 0.2, strength: 'weak' },
    ],
    records: [
      {
        id: 'rec-6',
        source_system: 'registry',
        source_id: 'REG-551',
        entity_type: 'company',
        name: 'Northern Grid AS',
        // observed_at: '2026-03-22T09:00:00Z',
        raw_payload_json: {
          registry_status: 'active',
        },
        record_subtype: 'legal_entity',
        record_family: 'organization',
        anchor_name: 'Northern Grid',
        client_name: 'Northern Grid AS',
        client_name_primary: 'Northern Grid AS',
        country: 'Estonia',
        address: 'Tartu',
        sector: 'Energy',
        reg_no: 'EE555222111',
        field_values: {
          phone: '+372 700 1234',
          email: 'contact@northerngrid.ee',
        },
      },
      {
        id: 'rec-7',
        source_system: 'crm',
        source_id: 'CRM-552',
        entity_type: 'company',
        name: 'Northern Grid Solutions',
        // observed_at: '2026-03-22T12:30:00Z',
        raw_payload_json: {
          lifecycle_stage: 'opportunity',
        },
        record_subtype: 'prospect_account',
        record_family: 'organization',
        anchor_name: 'NG Solutions',
        client_name: 'Northern Grid Solutions',
        client_name_primary: 'Northern Grid Solutions',
        country: 'Estonia',
        address: 'Tallinn',
        sector: 'Energy',
        reg_no: '',
        field_values: {
          phone: '+372 700 5678',
          email: 'sales@ngsolutions.ee',
        },
      },
    ],
    projects: [
      {
        id: 'proj-1003-a',
        source_system: 'Smartsheet',
        source_id: '1300949',
        project_name: 'QLAARA: arenduse nõustamine',
        project_title: 'QLAARA: arenduse nõustamine',
        project_state: 'Confirmed',
        project_start_date: '2017-01-01',
        project_end_date: '2017-12-31',
        company: 'Qlaara',
        project_code: '43',
        owner_name: 'Anna Kask',
        owner_email: 'anna.kask@qlaara.example',
        description: 'Preview card to validate project context placement in the review flow.',
      },
      {
        id: 'proj-1003-b',
        source_system: 'Smartsheet',
        source_id: '1300868',
        project_name: 'QLAARA: arendus',
        project_title: 'QLAARA: arendus',
        project_state: 'Confirmed',
        project_start_date: '2017-01-01',
        project_end_date: '2017-12-31',
        company: 'Qlaara',
        project_code: '19',
        owner_name: 'Karl Oja',
        owner_email: 'karl.oja@qlaara.example',
        description: '',
      },
    ],
  },
  {
    id: 'GRP-1004',
    confidence: 0.96,
    status: 'confirmed',
    assignee: 'Elen Axis',
    reasons: [
      { text: 'Registration number exact match', score: 1, strength: 'strong' },
      { text: 'Client name exact match', score: 0.95, strength: 'strong' },
      { text: 'Country matches', score: 0.7, strength: 'medium' },
    ],
    records: [
      {
        id: 'rec-8',
        source_system: 'registry',
        source_id: 'REG-700',
        entity_type: 'company',
        name: 'Bluewave Systems OÜ',
        // observed_at: '2026-03-16T10:00:00Z',
        raw_payload_json: { registry_status: 'active' },
        record_subtype: 'legal_entity',
        record_family: 'organization',
        anchor_name: 'Bluewave Systems',
        client_name: 'Bluewave Systems OÜ',
        client_name_primary: 'Bluewave Systems OÜ',
        country: 'Estonia',
        address: 'Tallinn',
        sector: 'Software',
        reg_no: 'EE700111222',
        field_values: {
          phone: '+372 611 2233',
          email: 'hello@bluewave.ee',
        },
      },
      {
        id: 'rec-9',
        source_system: 'crm',
        source_id: 'CRM-701',
        entity_type: 'company',
        name: 'Bluewave Systems OÜ',
        // observed_at: '2026-03-16T11:00:00Z',
        raw_payload_json: { lifecycle_stage: 'customer' },
        record_subtype: 'client_account',
        record_family: 'organization',
        anchor_name: 'Bluewave Systems',
        client_name: 'Bluewave Systems OÜ',
        client_name_primary: 'Bluewave Systems OÜ',
        country: 'Estonia',
        address: 'Tallinn',
        sector: 'Software',
        reg_no: 'EE700111222',
        field_values: {
          phone: '+372 611 2233',
          email: 'hello@bluewave.ee',
        },
      },
    ],
    projects: [
      {
        id: 'proj-1004-a',
        source_system: 'Smartsheet',
        source_id: '1300933',
        project_name: 'mWallet',
        project_title: 'mWallet',
        project_state: 'Confirmed',
        project_start_date: '2017-01-01',
        project_end_date: '2017-03-31',
        company: 'Kaubamaja',
        project_code: '27',
        owner_name: 'Liina Vaher',
        owner_email: 'liina.vaher@kaubamaja.example',
        description: 'Confirmed project preview for a fully resolved company group.',
      },
    ],
  },
]